language: python

matrix:
  include:
    - python: 2.7
      env: DJANGO="django<1.9"
    - python: 3.4
      env: DJANGO="django<1.9"
    - python: 3.5
      env: DJANGO="django<1.9"

    - python: 2.7
      env: DJANGO="django<1.11"
    - python: 3.4
      env: DJANGO="django<1.11"
    - python: 3.5
      env: DJANGO="django<1.11"

    - python: 2.7
      env: DJANGO="django<2"
    - python: 3.4
      env: DJANGO="django<2"
    - python: 3.5
      env: DJANGO="django<2"
    - python: 3.6
      env: DJANGO="django<2"

    - python: 3.4
      env: DJANGO="django"
    - python: 3.5
      env: DJANGO="django"
    - python: 3.6
      env: DJANGO="django"

install:
  - pip install --pre $DJANGO
  - pip install pytest-django pytest-cov codecov

script:
  - pytest -v --cov

after_success:
  - codecov
