language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

env:
  - DJANGO="django<1.9"
  - DJANGO="django<1.10"
  - DJANGO="django"

install:
  - pip install --pre $DJANGO
  - pip install pytest-django pytest-cov django-dynamic-fixture codecov

script:
  - py.test -v --cov

after_success:
  - codecov
