language: python

python:
  - 3.6
  - 3.7

env:
  - DJANGO="django<2"
  - DJANGO="django<3"
  - DJANGO="django"

matrix:
  include:
    - python: 2.7
      env: DJANGO="django<2"
    - python: 3.5
      env: DJANGO="django<2"
    - python: 3.5
      env: DJANGO="django<3"
    - python: 3.8
      env: DJANGO="django"

install:
  - pip install --pre $DJANGO
  - pip install pytest-django pytest-cov codecov

script:
  - pytest -v --cov

after_success:
  - codecov

deploy:
  provider: pypi
  user: coady
  password:
    secure: ahc9lUt4NcXN9zyxJct2u4BSBSkFKJcQwwA3MFDtjc/f60c2R5MZj2e1M90TGUwcjZeb06uHWWNybl+avFq/TjTlj/dygAhlnJ3SBrzQ4Et5Ncdu/ll0IZExRNEKb210Scw9KDTVs1ma63dw0xzWnH+Nbi9oebVKkM480s4f6bJDF0JWLKeahDnKSfg0dv7vQlhy6qFXOPN8EtWquBnSZNgRt9c+/HL/d6UE20nA5ajaiLgVr6hEnF+uVvl7PBz8UZCycuN+Qq+zGCOKu26rF6QpTf3eYcQxR6Ls1Ap1zI95P0pjUu4Sa8Tx30znJl9lBuN49D7G0JBLC8jNoT23r5n601sKOY3XEZE95djMkz6khLDMVEHDmHJErF5+vRnKPnIGsawWRicfam+j51FOoprifig7lFQJ4vWU5OE1KJHL9ULbjbyYcY4guaOnrUqj4rklcrUL5tvUPrVxs0qKSokNvP/cUnQEBZKabYNu6bEfyFtLV2WBV4BRyQiSEsqBHowsDq/MhT9EFUISaUZUgm6B+fdcjEFDrQFZ9d8ujqstD/xENlQDWm6eAn5ClRZC6TZqKnVDOLWCQhmCyFW8fx/n4JKPjPSJBvyVoA33/LTrBPCsigwKhmBpD0Ss5KhNkYD26blh8c0TMCa9jzC1EbtQFdNwnCHnkTJTThB/dGo=
  on:
    tags: true
  distributions: "sdist bdist_wheel"
  skip_existing: true
