language: python

python:
  - "2.7"
  - "3.4"

env:
  - DJANGO="django>=1.7,<1.8"
  - DJANGO="django>=1.8,<1.9"
  - DJANGO="django"

install:
  - pip install --pre $DJANGO
  - pip install pytest-django pytest-cov django-dynamic-fixture codecov

script:
  - py.test -v --cov

after_success:
  - codecov
